// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: protos/test.2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FOO int32

const (
	FOO_X FOO = 0
)

// Enum value maps for FOO.
var (
	FOO_name = map[int32]string{
		0: "X",
	}
	FOO_value = map[string]int32{
		"X": 0,
	}
)

func (x FOO) Enum() *FOO {
	p := new(FOO)
	*p = x
	return p
}

func (x FOO) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FOO) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_test_2_proto_enumTypes[0].Descriptor()
}

func (FOO) Type() protoreflect.EnumType {
	return &file_protos_test_2_proto_enumTypes[0]
}

func (x FOO) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FOO.Descriptor instead.
func (FOO) EnumDescriptor() ([]byte, []int) {
	return file_protos_test_2_proto_rawDescGZIP(), []int{0}
}

// 定义一种枚举类型
type PhoneType int32

const (
	//  option allow_alias = true; // 选项：是否可以定义别名
	PhoneType_MOBILE   PhoneType = 0
	PhoneType_HOME     PhoneType = 1
	PhoneType_WORK     PhoneType = 2
	PhoneType_Personal PhoneType = 3
)

// Enum value maps for PhoneType.
var (
	PhoneType_name = map[int32]string{
		0: "MOBILE",
		1: "HOME",
		2: "WORK",
		3: "Personal",
	}
	PhoneType_value = map[string]int32{
		"MOBILE":   0,
		"HOME":     1,
		"WORK":     2,
		"Personal": 3,
	}
)

func (x PhoneType) Enum() *PhoneType {
	p := new(PhoneType)
	*p = x
	return p
}

func (x PhoneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhoneType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_test_2_proto_enumTypes[1].Descriptor()
}

func (PhoneType) Type() protoreflect.EnumType {
	return &file_protos_test_2_proto_enumTypes[1]
}

func (x PhoneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhoneType.Descriptor instead.
func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return file_protos_test_2_proto_rawDescGZIP(), []int{1}
}

type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Type  int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Reps  int64    `protobuf:"varint,3,opt,name=reps,proto3" json:"reps,omitempty"`
	Phone []string `protobuf:"bytes,4,rep,name=phone,proto3" json:"phone,omitempty"` // 数组
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_test_2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_protos_test_2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_protos_test_2_proto_rawDescGZIP(), []int{0}
}

func (x *Test) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Test) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Test) GetReps() int64 {
	if x != nil {
		return x.Reps
	}
	return 0
}

func (x *Test) GetPhone() []string {
	if x != nil {
		return x.Phone
	}
	return nil
}

type Test2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	T *Test `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"` // 结构体嵌套
}

func (x *Test2) Reset() {
	*x = Test2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_test_2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test2) ProtoMessage() {}

func (x *Test2) ProtoReflect() protoreflect.Message {
	mi := &file_protos_test_2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test2.ProtoReflect.Descriptor instead.
func (*Test2) Descriptor() ([]byte, []int) {
	return file_protos_test_2_proto_rawDescGZIP(), []int{1}
}

func (x *Test2) GetT() *Test {
	if x != nil {
		return x.T
	}
	return nil
}

type Teacher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age     int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// 使用定义的结构体
	Phone  *Teacher_PhoneNumber   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Phones []*Teacher_PhoneNumber `protobuf:"bytes,5,rep,name=phones,proto3" json:"phones,omitempty"` // 数组
	// 如果有一个饱含许多字段的消息，并且只能同时设置一个字段，则可以使用oneof
	//
	// Types that are assignable to Data:
	//	*Teacher_School
	//	*Teacher_Score
	Data isTeacher_Data `protobuf_oneof:"data"`
}

func (x *Teacher) Reset() {
	*x = Teacher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_test_2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Teacher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teacher) ProtoMessage() {}

func (x *Teacher) ProtoReflect() protoreflect.Message {
	mi := &file_protos_test_2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teacher.ProtoReflect.Descriptor instead.
func (*Teacher) Descriptor() ([]byte, []int) {
	return file_protos_test_2_proto_rawDescGZIP(), []int{2}
}

func (x *Teacher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Teacher) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Teacher) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Teacher) GetPhone() *Teacher_PhoneNumber {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *Teacher) GetPhones() []*Teacher_PhoneNumber {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (m *Teacher) GetData() isTeacher_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Teacher) GetSchool() string {
	if x, ok := x.GetData().(*Teacher_School); ok {
		return x.School
	}
	return ""
}

func (x *Teacher) GetScore() int32 {
	if x, ok := x.GetData().(*Teacher_Score); ok {
		return x.Score
	}
	return 0
}

type isTeacher_Data interface {
	isTeacher_Data()
}

type Teacher_School struct {
	School string `protobuf:"bytes,6,opt,name=school,proto3,oneof"`
}

type Teacher_Score struct {
	Score int32 `protobuf:"varint,7,opt,name=score,proto3,oneof"`
}

func (*Teacher_School) isTeacher_Data() {}

func (*Teacher_Score) isTeacher_Data() {}

// 定义一个结构体
type Teacher_PhoneNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type   int64  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Teacher_PhoneNumber) Reset() {
	*x = Teacher_PhoneNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_test_2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Teacher_PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teacher_PhoneNumber) ProtoMessage() {}

func (x *Teacher_PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_protos_test_2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teacher_PhoneNumber.ProtoReflect.Descriptor instead.
func (*Teacher_PhoneNumber) Descriptor() ([]byte, []int) {
	return file_protos_test_2_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Teacher_PhoneNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Teacher_PhoneNumber) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

var File_protos_test_2_proto protoreflect.FileDescriptor

var file_protos_test_2_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x32, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x65, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x22, 0x1c, 0x0a, 0x05, 0x54, 0x65, 0x73, 0x74, 0x32, 0x12, 0x13, 0x0a, 0x01, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x01, 0x74, 0x22,
	0x98, 0x02, 0x0a, 0x07, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x54, 0x65, 0x61,
	0x63, 0x68, 0x65, 0x72, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65,
	0x72, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x12,
	0x16, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x39, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x0c, 0x0a, 0x03, 0x46, 0x4f,
	0x4f, 0x12, 0x05, 0x0a, 0x01, 0x58, 0x10, 0x00, 0x2a, 0x39, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57,
	0x4f, 0x52, 0x4b, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x6c, 0x10, 0x03, 0x32, 0x2b, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x08, 0x2e, 0x54,
	0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x1a, 0x08, 0x2e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_test_2_proto_rawDescOnce sync.Once
	file_protos_test_2_proto_rawDescData = file_protos_test_2_proto_rawDesc
)

func file_protos_test_2_proto_rawDescGZIP() []byte {
	file_protos_test_2_proto_rawDescOnce.Do(func() {
		file_protos_test_2_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_test_2_proto_rawDescData)
	})
	return file_protos_test_2_proto_rawDescData
}

var file_protos_test_2_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_test_2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_test_2_proto_goTypes = []interface{}{
	(FOO)(0),                    // 0: FOO
	(PhoneType)(0),              // 1: PhoneType
	(*Test)(nil),                // 2: Test
	(*Test2)(nil),               // 3: Test2
	(*Teacher)(nil),             // 4: Teacher
	(*Teacher_PhoneNumber)(nil), // 5: Teacher.PhoneNumber
}
var file_protos_test_2_proto_depIdxs = []int32{
	2, // 0: Test2.t:type_name -> Test
	5, // 1: Teacher.phone:type_name -> Teacher.PhoneNumber
	5, // 2: Teacher.phones:type_name -> Teacher.PhoneNumber
	4, // 3: HelloService.World:input_type -> Teacher
	4, // 4: HelloService.World:output_type -> Teacher
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_test_2_proto_init() }
func file_protos_test_2_proto_init() {
	if File_protos_test_2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_test_2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_test_2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_test_2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Teacher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_test_2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Teacher_PhoneNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_test_2_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Teacher_School)(nil),
		(*Teacher_Score)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_test_2_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_test_2_proto_goTypes,
		DependencyIndexes: file_protos_test_2_proto_depIdxs,
		EnumInfos:         file_protos_test_2_proto_enumTypes,
		MessageInfos:      file_protos_test_2_proto_msgTypes,
	}.Build()
	File_protos_test_2_proto = out.File
	file_protos_test_2_proto_rawDesc = nil
	file_protos_test_2_proto_goTypes = nil
	file_protos_test_2_proto_depIdxs = nil
}
